export enum ENVEnum {
    NODE_ENV = 'NODE_ENV',
    DATABASE_URL='DATABASE_URL',
    PORT='PORT',
    BASE_URL='BASE_URL',
    JWT_SECRET='JWT_SECRET',
    JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
    REFRESH_TOKEN_LENGTH = 'REFRESH_TOKEN_LENGTH',
    REFRESH_TOKEN_EXPIRES_DAYS = 'REFRESH_TOKEN_EXPIRES_DAYS',

    FRONTEND_URL = 'FRONTEND_URL',

    MAIL_USER = 'MAIL_USER',
    MAIL_PASS = 'MAIL_PASS',

    REDIS_HOST = 'REDIS_HOST',
    REDIS_PORT = 'REDIS_PORT',
    REDIS_USERNAME = 'REDIS_USERNAME',
    REDIS_PASSWORD = 'REDIS_PASSWORD',

    STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY',
    STRIPE_WEBHOOK_SECRET = 'STRIPE_WEBHOOK_SECRET',

    GOOGLE_MAPS_API_KEY = 'GOOGLE_MAPS_API_KEY',

    FIREBASE_ENABLED = 'FIREBASE_ENABLED',
    FIREBASE_PROJECT_ID = 'FIREBASE_PROJECT_ID',
    FIREBASE_CLIENT_EMAIL = 'FIREBASE_CLIENT_EMAIL',
    FIREBASE_PRIVATE_KEY = 'FIREBASE_PRIVATE_KEY',

    SUPER_ADMIN_EMAIL = 'SUPER_ADMIN_EMAIL',
    SUPER_ADMIN_PASS = 'SUPER_ADMIN_PASS',

    AWS_REGION = 'AWS_REGION',
    AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
    AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
    AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET_NAME',
}